// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK3c3KPCVb20uqAIUKSdvXNvz1mAmAxhw',
    appId: '1:746630531412:web:57fa8132860d88492560c1',
    messagingSenderId: '746630531412',
    projectId: 'minorproject01-29ca6',
    authDomain: 'minorproject01-29ca6.firebaseapp.com',
    storageBucket: 'minorproject01-29ca6.appspot.com',
    measurementId: 'G-QNEJ6ZCL0Z',
    databaseURL: 'https://console.firebase.google.com/project/minorproject01-29ca6/firestore/databases/-default-/data/~2Fusers~2FZErN7MBJDAM2hN2rbKmd225eiVA2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbk5qBhZcH7vsDgQ01OAqUSN9eR8D3X0M',
    appId: '1:746630531412:android:97832c7cbd90f0162560c1',
    messagingSenderId: '746630531412',
    projectId: 'minorproject01-f9043',
    storageBucket: 'minorproject01-f9043.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEuyVNQFUDbylapUpU1SkA1CBG5iAJbDE',
    appId: '1:746630531412:ios:342d4ef5e8f368702560c1',
    messagingSenderId: '746630531412',
    projectId: 'minorproject01-f9043',
    storageBucket: 'minorproject01-f9043.appspot.com',
    iosBundleId: 'com.tiny.minorproject01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEuyVNQFUDbylapUpU1SkA1CBG5iAJbDE',
    appId: '1:746630531412:ios:342d4ef5e8f368702560c1',
    messagingSenderId: '746630531412',
    projectId: 'minorproject01-f9043',
    storageBucket: 'minorproject01-f9043.appspot.com',
    iosBundleId: 'com.tiny.minorproject01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbjeRbjzvKw7CtB8_dHP62F7dILFhtKU8',
    appId: '1:746630531412:web:656afb6ea286ef632560c1',
    messagingSenderId: '746630531412',
    projectId: 'minorproject01-f9043',
    authDomain: 'minorproject01-f9043.firebaseapp.com',
    storageBucket: 'minorproject01-f9043.appspot.com',
    measurementId: 'G-92EEF6CEV3',
  );
}
